bus_name_mapping:
  2:
    03000200-0400-0500-0006-000700080009:
      usb-0000:00:14.0-1: follow_camera
      usb-0000:00:14.0-4: env_camera
    b0dc8900-3b32-11ed-99b1-ef6412dd1a00:
      '243322072294': env_camera
      '427622274177': follow_camera
      usb-0000:00:14.0-3: env_camera
      usb-0000:00:14.0-5: follow_camera
    c5bc8546-51a9-21a3-9b32-1c697aa5e070:
      usb-0000:00:14.0-2: follow_camera
      usb-0000:00:14.0-3: env_camera
  4:
    2f65ca50-4038-4964-8c95-fc5cee443bea:
      usb-0000:00:14.0-11.1: env_camera
      usb-0000:00:14.0-11.3: left_camera
      usb-0000:00:14.0-4: right_camera
    39e638a7-4129-11ec-80f0-84a938a80e50:
      usb-0000:00:14.0-1: right_camera
      usb-0000:00:14.0-3.1: env_camera
      usb-0000:00:14.0-3.3: left_camera
    62861f46-94eb-43f2-bc3b-c4efbbf6083e:
      usb-0000:00:14.0-13.3: right_camera
      usb-0000:00:14.0-4: env_camera
      usb-0000:00:14.0-8: left_camera
# NOTE: The 2 and 4 below refer to the number of robotic arms. During automatic setup,
# the number of robotic arms determines the available camera names.
    cbbe5710-6042-8a12-afa6-345a6012961e:
      '142122070505': env_camera
      '153222071023': right_camera
      '213622078851': left_camera
choices:
  false: # not drag
    2: # 1 * (leader + follower)
    - follow_camera
    - env_camera
    4: # 2 * (leader + follower)
    - left_camera
    - right_camera
    - env_camera
    # - front_camera
    # - top_camera
  true: # drag
    1: # single arm
    - follow_camera
    - env_camera
    2: # left + right arms
    - left_camera
    - right_camera
    - env_camera
    # - front_camera
    # - top_camera
